<a href="https://colab.research.google.com/github/RashikaTyagi01/Rashika-UML501/blob/main/MLassignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1: Questions on Basic NumPy Array

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [1]:
import numpy as np
arr = np.array([1,2,3,6,4,5])
print("Reversed array: ", np.flip(arr))

Reversed array:  [5 4 6 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [2]:
array1 = np.array([[1,2,3], [2,4,5], [1,2,3]])
print("Flattened array: ", array1.flatten())

print("Flattened array: ", np.ravel(array1))


Flattened array:  [1 2 3 2 4 5 1 2 3]
Flattened array:  [1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [3]:
a1 = np.array([[1,2], [3,4]])
a2 = np.array([[1,2], [3,4]])
print(a1==a2)
print(np.array_equal(a1,a2))

print(np.equal(a1,a2))

[[ True  True]
 [ True  True]]
True
[[ True  True]
 [ True  True]]


(d) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [4]:
#i)
x = np.array([1,2,3,4,5,1,2,1,1,1])
ele = np.bincount(x).argmax()
print(ele)
print(np.where(x==ele)[0])

1
[0 5 7 8 9]


In [5]:
#ii)
y = np.array([1,1,1,2,3,4,2,2,3,3])
occ = np.bincount(y)
maximum = max(occ)
for i in range(len(occ)):
  if(occ[i]==maximum):
    print("freq value:",i, end=" ")
    print("indices:",np.where(y==i)[0])

freq value: 1 indices: [0 1 2]
freq value: 2 indices: [3 6 7]
freq value: 3 indices: [4 8 9]


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise

In [6]:
gfg = np.matrix('[4,1,9; 12,3,1; 4,5,6]')
#i)
print(np.sum(gfg))
#ii)
print("row-wise sum: ")
print(np.sum(gfg, axis=1))
#iii)
print("column-wise sum: ",np.sum(gfg, axis=0))

45
row-wise sum: 
[[14]
 [16]
 [15]]
column-wise sum:  [[20  9 16]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
i. Sum of diagonal elements
ii. Eigen values of matrix
iii. Eigen vectors of matrix
iv. Inverse of matrix
v. Determinant of matrix

In [7]:
n_array = np.array([[55,25,15],[30,44,2],[11,45,77]])
print("Diagonal sum: ", np.trace(n_array),"\n")
vector,value = np.linalg.eig(n_array)
print("eigen values: ",value)
print("eigen vectors: ",vector)
print()
print("inverse of matrix: ")
print(np.linalg.inv(n_array),"\n")
print("determinant: ",np.linalg.det(n_array))

Diagonal sum:  176 

eigen values:  [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
eigen vectors:  [98.16835147 28.097044   49.73460452]

inverse of matrix: 
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]] 

determinant:  137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy:
i. p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
ii. p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]

In [8]:
#i)
p = np.array([[1,2],[2,3]])
q = np.array([[4,5],[6,7]])
mul1 = np.matmul(p,q)
print("Matrix multiplication: ")
print(mul1)

cov1 = np.cov(p.flatten(),q.flatten())
print("Covariance: ")
print(cov1)

Matrix multiplication: 
[[16 19]
 [26 31]]
Covariance: 
[[0.66666667 1.        ]
 [1.         1.66666667]]


In [9]:
#ii)
p1 = np.array([[1,2],[2,3],[4,5]])
q1 = np.array([[4,5,1],[6,7,2]])
mul2 = np.matmul(p1,q1)
print("Matrix multiplication: ")
print(mul2)
cov2 = np.cov(p1.flatten(),q1.flatten())
print("Covariance: ")
print(cov2)

Matrix multiplication: 
[[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance: 
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

In [10]:
x=np.array([[2,3,4],[3,2,9]])
y=np.array([[1,5,0],[5,10,3]])
print("Inner product: ",np.inner(x,y))
print("Outer product: ",np.outer(x,y))

from itertools import product
cartesian = np.array(list(product(x.flatten(),y.flatten())))
print("Cartesian product: \n",cartesian)

Inner product:  [[17 52]
 [13 62]]
Outer product:  [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product: 
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


Q2: Based on NumPy Mathematics and Statistics
(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
i. Find element-wise absolute value
ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.
iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row

In [11]:
array = np.array([[1,-2,3],[-4,5,-6]])
print(np.absolute(array))
print()

print("for flattened array: ")
flat = array.flatten();
print("25th percentile: ",np.percentile(flat,25))
print("50th percentile: ",np.percentile(flat,50))
print("75th percentile: ",np.percentile(flat,75),"\n")
print("for each column: ")
print("25th percentile: ",np.percentile(array,25,axis=0))
print("50th percentile: ",np.percentile(array,50,axis=0))
print("75th percentile: ",np.percentile(array,75,axis=0),"\n")
print("for each row: ",)
print("25th percentile: ",np.percentile(array,25,axis=1))
print("50th percentile: ",np.percentile(array,50,axis=1))
print("75th percentile: ",np.percentile(array,75,axis=1),"\n")

print("for flattened array: ")
print("mean: ",np.mean(flat))
print("median: ",np.median(flat))
print("standard deviation: ",np.std(flat),"\n")
print("for each column: ")
print("mean: ",np.mean(array,axis=0))
print("median: ",np.median(array,axis=0))
print("standard deviation: ",np.std(array,axis=0),"\n")
print("for each row: ",)
print("mean: ",np.mean(array,axis=1))
print("median: ",np.median(array,axis=1))
print("standard deviation: ",np.std(array,axis=1))


[[1 2 3]
 [4 5 6]]

for flattened array: 
25th percentile:  -3.5
50th percentile:  -0.5
75th percentile:  2.5 

for each column: 
25th percentile:  [-2.75 -0.25 -3.75]
50th percentile:  [-1.5  1.5 -1.5]
75th percentile:  [-0.25  3.25  0.75] 

for each row: 
25th percentile:  [-0.5 -5. ]
50th percentile:  [ 1. -4.]
75th percentile:  [2.  0.5] 

for flattened array: 
mean:  -0.5
median:  -0.5
standard deviation:  3.8622100754188224 

for each column: 
mean:  [-1.5  1.5 -1.5]
median:  [-1.5  1.5 -1.5]
standard deviation:  [2.5 3.5 4.5] 

for each row: 
mean:  [ 0.66666667 -1.66666667]
median:  [ 1. -4.]
standard deviation:  [2.05480467 4.78423336]


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [12]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("floor: ",np.floor(a))
print("ceiling: ",np.ceil(a))
print("truncated: ",np.trunc(a))
print("rounded values: ",np.round(a))

floor:  [-2. -2. -1.  0.  1.  1.  3.]
ceiling:  [-1. -1. -0.  1.  2.  2.  3.]
truncated:  [-1. -1. -0.  0.  1.  1.  3.]
rounded values:  [-2. -2. -0.  0.  2.  2.  3.]


Q3: Based on Searching and Sorting
(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
i. Sorted array
ii. Indices of sorted array
iii. 4 smallest elements
iv. 5 largest elements

In [13]:
arr1 = np.array([10,52,62,16,16,54,453])
print("sorted array: ",np.sort(arr1))
print("indices of sorted array: ",np.argsort(arr1))
sorted = np.sort(arr1)
print("4 smallest elements: ",sorted[:4])
print("5 largest elements: ",sorted[-5:])

sorted array:  [ 10  16  16  52  54  62 453]
indices of sorted array:  [0 3 4 1 5 2 6]
4 smallest elements:  [10 16 16 52]
5 largest elements:  [ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
i. Integer elements only
ii. Float elements only

In [14]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print("integer elements: ",array[array == array.astype(int)])
print("Float elements: ",array[array != array.astype(int)])

integer elements:  [1. 2. 3. 2.]
Float elements:  [1.2 2.2]


Q4:
(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)
(b) Load the saved file into jupyter notebook?

In [15]:
import numpy as np
from PIL import Image
def img_to_array(path):
  img = Image.open(path)
  arr = np.array(img)
  if len(arr.shape) == 2:
    np.savetxt("grayscale_image.txt",arr,fmt='%d')
    print("grayscale image saved")
  else:
    np.savetxt("rgb_image.txt",arr.reshape(-1,arr.shape[2]),fmt='%d')
    print("flattened rgb image saved")

def load(filename):
  arr=np.loadtxt(filename,dtype=int)
  print(f"Loaded {filename}")
  return arr